name: on-push
on: [push, pull_request]
jobs:
  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Latest released and oldest supported.
        node: [18, 14]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js & Yarn
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Typecheck
        run: yarn typecheck
      - name: Lint
        run: yarn lint
      - name: Check formatting
        run: yarn fmt --check
      - name: Test
        if: matrix.node == 18
        run: yarn test
      # Older versions of Node aren't as good at detecting coverage.
      - name: Test w/o coverage
        if: matrix.node == 14
        run: yarn test --coverage=false
      - name: Docs
        run: yarn docs
